# Generated by Django 2.0.6 on 2018-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edufox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactNumber', models.IntegerField(max_length=14)),
                ('YourName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('CourseName', models.CharField(max_length=20)),
            ],
        ),
    ]
